///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CommentCreateModel {
/*
{
  "tripId": 0,
  "userId": 0,
  "comment": "string",
  "point": 0
} 
*/

  late int tripId;
  late int userId;
  late String comment;
  late int point;

  CommentCreateModel({
    required this.tripId,
    required this.userId,
    required this.comment,
    required this.point,
  });
  CommentCreateModel.fromJson(Map<String, dynamic> json) {
    tripId = json['tripId']?.toInt();
    userId = json['userId']?.toInt();
    comment = json['comment'].toString();
    point = json['point']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['tripId'] = tripId;
    data['userId'] = userId;
    data['comment'] = comment;
    data['point'] = point;
    return data;
  }
}
